LIB    = libglodb.lib
CC     = bcc32
AR     = tlib
CFLAGS = -I../machine -I../win32

OBJS=	bt_close.obj bt_conv.obj bt_debug.obj bt_delete.obj bt_get.obj \
	bt_open.obj bt_overflow.obj bt_page.obj bt_put.obj bt_search.obj \
	bt_seq.obj bt_split.obj bt_utils.obj mpool.obj db.obj

all: $(LIB)

$(LIB): $(OBJS)
	$(AR) $(LIB) @..\win32\dbobjs
install:
	@echo -n
clean:
	del *.lib
	del *.obj
