.\" Hey Emacs! This file is -*- nroff -*- source.
.TH SYSTAGS 1
.SH NAME
systags \- script to make hypertext of kernel source
.SH SYNOPSIS
.B systags
[-c|-C] [-f] [-g] [-n] [\fIdir\fP]
.SH "DESCRIPTION"
This manual page documents briefly the
.BR systags
command.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B systags
is a script that generates a tagged html version of a source code
directory.  The script is specially prepared to work with the source
of FreeBSD, NetBSD, OpenBSD, Linux, GNUmach and GNUhurd.
.PP
.B systags
invokes htags(1) with \fB-lhna\fP options, which can significantly
increase the size of the html tree produced.
.PP
To build the HTML tree the command must be called from the root of the
source tree.
.SH OPTIONS
.TP
.B \-c
Compress html files  by gzip(1). The option is passed to the htags(1) command.
.TP
.B \-C
Option passed to htags(1) to produce compressed files with html.gz suffix.
This may be preferred to \fB-c\fP on Debian GNU/Linux systems.
.TP
.B \-g
Generate only the databases needed by global(1). Basically it only
executes the gtags(1) command.
.TP
.B \-f
Support an input form and a dynamic index with a CGI program.  The option is
passed to the htags(1) command.
.TP
.B \-n
Run in test mode. Shows the commands that the script calls to do its work, but
does not execute them.
.TP
.B dir
The directory in which hypertext is generated. The default is the current
directory.
.SH EXAMPLES
To generate a compressed browseable version of the linux kernel on a
Debian system you can do:
.PP
.br
\fB    cd /usr/src/linux\fP
\fB    systags\fP
.br
.SH "SEE ALSO"
\fBglobal\fP(1),
\fBgtags\fP(1),
\fBhtags\fP(1).
.SH AUTHOR
This manual page was written by Sergio Talens-Oliag <sto@iti.upv.es>,
for the Debian GNU/Linux system (but may be used by others).
