.TH GLOBASH 1 "6 August 2005" "Debian GNU/Linux" "GLOBAL Utilities"
.\" Copyright (c) 2005  Ron Lee.  All rights reserved.
.\" This text may be distributed under the same terms as the GLOBAL source.
.\" All copies of this manual must acknowledge the author and include the
.\" above copyright statement.
.\"
.SH NAME
globash \- invoke a GLOBAL shell environment.
.SH SYNOPSIS
.B globash
.SH "DESCRIPTION"
.B globash
is a \fBbash\fP shell enviroment that provides easy access to \fBGLOBAL\fP
data about a project.  More information about its use is available in the
\fIglobal.info\fP documentation, and from \fBglobash\fP itself at any time
with the \fBghelp\fP command that is available from inside it.
.SH OPTIONS
There are no options.  Or blue pills.
Just a simple shortcut to a bigger shell game.
.SH FILES
.I /etc/globash.rc
\- where all the real machinery lives.
.SH BUGS
As a wrapper \fBglobash\fP gets to inherit bugs from other software too.
But its hardly big enough to have many on its own.
.SH "SEE ALSO"
.BR gtags (1), " global" (1), " htmake" (1), " htags" (1),
.br
and the \fBglobal\fP info documentation.
.SH AUTHOR
Ron Lee <ron@debian.org>, wrote this manpage, added the \fBglobash\fP wrapper,
and made a few minor tweaks to the \fIglobash.rc\fP file which does all the
real work and was written by Shigio Yamaguchi.
