LIB    = libgloregex.a
CC     = gcc
AR     = ar
CFLAGS = -O -I../machine
OBJS   = regcomp.o regerror.o regexec.o regfree.o

all: $(LIB)

$(LIB): $(OBJS)
	$(AR) cr $(LIB) $(OBJS)
install:
	@echo -n
cygwin_install:
	@echo -n
clean:
	rm -f $(LIB) $(OBJS)
