LIB    = libgloutil.a
CC     = gcc
AR     = ar
CFLAGS = -O -I../libdb -I../libregex -I../machine
OBJS   = usable.o gtagsop.o getdbpath.o find.o defined.o conf.o tab.o \
	 strmake.o pathop.o mgets.o makepath.o locatestring.o dbop.o \
	 test.o token.o strbuf.o path.o

all: $(LIB)

$(LIB): $(OBJS)
	$(AR) cr $(LIB) $(OBJS)
install:
	@echo -n
cygwin_install:
	@echo -n
clean:
	rm -f $(LIB) $(OBJS)
