LIB    = libgloutil.lib
CC     = bcc32
AR     = tlib
CFLAGS = -I../libutil -I../libdb -I../libregex -I../machine -I../win32
OBJS   = usable.obj gtagsop.obj getdbpath.obj find.obj defined.obj \
	 conf.obj tab.obj strmake.obj pathop.obj mgets.obj makepath.obj \
	 locatestring.obj dbop.obj test.obj token.obj strbuf.obj path.obj

all: $(LIB)

$(LIB): $(OBJS)
	$(AR) $(LIB) @..\win32\utilobjs
install:
	@echo -n
clean:
	del *.lib
	del *.obj
