# This part is generated automatically by convert.pl from htags/manual.in.
$program = 'htags';
$usage_const = "Usage: htags [-a][-c][-f][-F][-g][-m][-n][-o][-s][-v][-w][-d dir][-S dir][-t title][dir]";
$help_const = "$usage_const\
Options:\
-a, --alphabet\
       Make an alphabetical function index, suitable for a large project.\
--caution\
       Include caution message to prohibit downloading.\
-c, --compact\
       Compress html files  by gzip(1).\
       You need to set up an HTTP server so that gzip(1)\
       is invoked for each compressed file.\
       See 'HTML/.htaccess' that is generated by htags.\
-d, --dbpath dir\
       Specifies the directory in which 'GTAGS' and 'GRTAGS'\
       exist. The default is the current directory.\
-f, --form\
       Support search form using CGI program.\
       You need to set up an HTTP server for this.\
-F, --frame\
       Use frame for each part of the contents.\
-g, --gtags\
       Execute gtags(1) before creating hypertext.\
--gtagsconf file\
       Load user's configuration from file.\
-m, --main-func\
       Specify the main function name. The default is main.\
-n, --line-number\
       Print the line numbers. By default, doesn't print it.\
--no-javascript\
       Doesn't put javascript code.\
       By default, htags put javascript code.\
-o, --other\
       Pick up not only source files but also other files except for\
       binary files.\
--style-sheet file\
       Load style sheet file and insert it into <HEAD> tag.\
-s, --symbols\
       Make anchors not only for functions but also other symbols.\
       'GSYMS' tag file needed.\
-S, --secure-cgi dir\
       write cgi script into dir to realize a centralised\
       cgi script. Script alias is '/cgi-bin' by default.\
       You can overwrite this value with config variable\
       script_alias in 'gtags.conf'.\
-t, --title title\
       The title of this hypertext. The default is the last\
       component of the current directory.\
-v, --verbose\
       Verbose mode.\
-w, --warning\
       Print warning messages.\
dir\
       The directory in which hypertext is generated.\
       The default is the current directory.\
";
# end of generated part.
