/* This file is generated automatically by convert.pl from htags/manual.in. */
const char *progname = "htags";
const char *usage_const = "Usage: htags [-a][-c][-D][-f][-F][-g][-n][-o][-s][-v][-w][-x][-d dbpath][-m name][-S cgidir][-t title][htmldir]\n";
const char *help_const = "Options:\n\
-a, --alphabet\n\
       Make an alphabetical function index which is suitable\n\
       for a large project.\n\
--caution\n\
       Include caution message to prohibit downloading.\n\
-c, --compact\n\
       Compress html files  by gzip(1).\n\
       You need to set up a web server so that gzip(1)\n\
       is invoked for each compressed file.\n\
       See HTML/.htaccess that is generated by htags.\n\
--cvsweb url\n\
       Include cvsweb URL. url is used as base of URL.\n\
--cvsweb-cvsroot cvsroot\n\
       Specifies cvsroot in cvsweb URL.\n\
-D, --dynamic\n\
       Generate object lists dynamically using CGI program.\n\
       By default, object lists are generated statically.\n\
       Though this option decrease both the size and the generation\n\
       time of the hypertext, you need to set up a web server, and \n\
       you cannot move the hypertext from the source directroy.\n\
-d, --dbpath dbpath\n\
       Specifies the directory in which GTAGS and GRTAGS\n\
       exist. The default is the current directory.\n\
-f, --form\n\
       Support search form using CGI program.\n\
       You need to set up a web server, and you cannot move\n\
       the hypertext from the source directroy.\n\
-F, --frame\n\
       Use frame for each part of the contents.\n\
-g, --gtags\n\
       Execute gtags(1) before creating hypertext.\n\
       The -v, -w and dbpath are passed to gtags.\n\
--gtagsconf file\n\
       Load user's configuration from file.\n\
--gtagslabel label\n\
       label is used for the label of configuration file.\n\
       The default is default.\n\
--insert-header file\n\
       Insert custom header derived from file after <body> tag.\n\
--insert-footer file\n\
       Insert custom footer derived from file before </body> tag.\n\
-m, --main-func name\n\
       Specify the main function name. The default is main.\n\
-n, --line-number\n\
       Print line numbers. By default, doesn't print them.\n\
--no-map-file\n\
       Doesn't generate MAP and FILEMAP file.\n\
       By default, htags generates them.\n\
-o, --other\n\
       Pick up not only source files but also other files except for\n\
       binary files.\n\
--statistics\n\
       Print statistics information.\n\
--style-sheet file\n\
       Load style sheet file and insert it into <head> tag.\n\
       If you use the --xhtml option, you should use\n\
       style.css instead.\n\
-s, --symbol\n\
       Make anchors not only for functions but also other symbols.\n\
       GSYMS tag file needed.\n\
-S, --secure-cgi cgidir\n\
       Write CGI programs into the cgidir to realize\n\
       a centralised CGI program.\n\
       Script alias is /cgi-bin by default.\n\
       You can overwrite this value using config variable\n\
       script_alias in gtags.conf.\n\
-t, --title title\n\
       The title of this hypertext. The default is the last\n\
       component of the current directory.\n\
-v, --verbose\n\
       Verbose mode.\n\
-w, --warning\n\
       Print warning messages.\n\
-x, --xhtml\n\
       Generate XHTML hypertext instead of HTML.\n\
       If the --frame option is specified then\n\
       generate XHTML-1.0 Frameset for index.html\n\
       and generate XHTML-1.0 Transitional for other files,\n\
       else if config variable\n\
       xhtml_version is set to 1.1 then generate\n\
       XHTML-1.1 else XHTML 1.0 Transitional.\n\
htmldir\n\
       The directory in which hypertext is generated.\n\
       The default is the current directory.\n\
";
